### ISSUE TITLE
Installing from pypi does not work

### ISSUE THREAD

**Issue by ajfriesen** [VarMonke/GitHub-API-Wrapper#15]
### Summary

pip install github from pypi does not work

### Reproduction Steps

Just installing the package form pypi will not work.
I am using python 3.10.5
```
pip install github
```

### Minimal Reproducible Code

```Python
pip install github
```
```


### Expected Results

I expected the pip install not to fail.

### Actual Results

```
pip install github
Collecting github
  Using cached github-1.2.4.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/andrej/.pyenv/versions/3.10.5/envs/curated/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/andrej/.pyenv/versions/3.10.5/envs/curated/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/andrej/.pyenv/versions/3.10.5/envs/curated/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-825ng7yu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-825ng7yu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-825ng7yu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-825ng7yu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 5, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by VarMonke** [comment]
Hello. Sorry for the issue.
I'll try to figure it out as soon as possible. You can install the package using
`py -m pip install -U git+https://github.com/VarMonke/Github-Api-Wrapper` if Windows
`python3 -m pip install -U git+https://github.com/VarMonke/Github-Api-Wrapper` OR `python3.x -m pip install -U git+https://github.com/VarMonke/Github-Api-Wrapper` (x being the minor python version) if Linux/Unix

**Comment by ajfriesen** [comment]
No worries.
I have helped myself by adding the package with the git format to my `requirements.txt` file:
```
git+https://github.com/VarMonke/Github-Api-Wrapper@72df28268493ac03fb221f2e84e6ca752d3027f2
```

No blocker there. Just thought you want to know.

**Comment by VarMonke** [comment]
Yep, Thank you!
