### ISSUE TITLE
Commit 573617a breaks pip installation

### ISSUE THREAD

**Issue by flow3d** [VarMonke/GitHub-API-Wrapper#16]
### Summary

The lookup of requirements.txt breaks pip.

### Reproduction Steps

`pip install github`
Yields:
```Collecting github
  Downloading github-1.2.6.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/flow3d/work/env/newco/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/flow3d/work/env/newco/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/flow3d/work/env/newco/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/2k/2z863nrj47s2myzfzgccq6b80000gn/T/pip-build-env-qoa8uz88/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/2k/2z863nrj47s2myzfzgccq6b80000gn/T/pip-build-env-qoa8uz88/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2k/2z863nrj47s2myzfzgccq6b80000gn/T/pip-build-env-qoa8uz88/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/2k/2z863nrj47s2myzfzgccq6b80000gn/T/pip-build-env-qoa8uz88/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 4, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

### Minimal Reproducible Code

_No response_

### Expected Results

package installed

### Actual Results

package not installed

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by amcsparron2793-Water** [comment]
seems to work now on my end
